### ISSUE TITLE
Basketball example is not working

### ISSUE THREAD

**Issue by suyashcjoshi** [dyn4j/dyn4j-samples#2]
Hello,

I was excited to try this framework today and the first project I tried to run did not run and crashed with this runtime exception. Stacktrace pasted below that shows error in detail:

```
/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=51050:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/suyash.joshi/Downloads/dyn4j-samples-master/target/classes:/Users/suyash.joshi/.m2/repository/org/jogamp/jogl/jogl-all/2.3.2/jogl-all-2.3.2.jar:/Users/suyash.joshi/.m2/repository/org/jogamp/gluegen/gluegen-rt/2.3.2/gluegen-rt-2.3.2.jar:/Users/suyash.joshi/.m2/repository/org/dyn4j/dyn4j/4.2.0/dyn4j-4.2.0.jar org.dyn4j.samples.BasketBall
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1400)
	at org.dyn4j.samples.BasketBall.getImageSuppressExceptions(BasketBall.java:74)
	at org.dyn4j.samples.BasketBall.<clinit>(BasketBall.java:69)

```

**Comment by wnbittle** [comment]
I would check to make sure that the org/dyn4j/samples/resources/Basketball.png made it to the output folder when you built the project.  That error is telling you that it couldn't find the image to load on the classpath.

**Comment by wnbittle** [comment]
Closing due to no response
