### ISSUE TITLE
JOGL sample UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by scaventz** [dyn4j/dyn4j-samples#5]
Errors I got: 
```
C:\Users\scaventz\.gradle\jdks\jdk8u312-b07\bin\java.exe -javaagent:D:\IDE\JetBrains\apps\IDEA-C\ch-0\222.3739.54\lib\idea_rt.jar=60297:D:\IDE\JetBrains\apps\IDEA-C\ch-0\222.3739.54\bin -Dfile.encoding=UTF-8 -classpath C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\charsets.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\ext\access-bridge-64.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\ext\cldrdata.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\ext\dnsns.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\ext\jaccess.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\ext\localedata.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\ext\nashorn.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\ext\sunec.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\ext\sunjce_provider.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\ext\sunmscapi.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\ext\sunpkcs11.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\ext\zipfs.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\jce.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\jfr.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\jsse.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\management-agent.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\resources.jar;C:\Users\scave\.gradle\jdks\jdk8u312-b07\jre\lib\rt.jar;D:\Repos\dyn4j-samples\target\classes;C:\Users\scave\.m2\repository\org\jogamp\jogl\jogl-all\2.3.2\jogl-all-2.3.2.jar;C:\Users\scave\.m2\repository\org\jogamp\gluegen\gluegen-rt\2.3.2\gluegen-rt-2.3.2.jar;C:\Users\scave\.m2\repository\org\dyn4j\dyn4j\4.2.0\dyn4j-4.2.0.jar org.dyn4j.samples.UsingJogl
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: D:\Repos\dyn4j-samples\natives\windows-amd64\\gluegen-rt.dll
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1820)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:624)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:63)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:106)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:487)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:421)
	at com.jogamp.common.os.Platform$1.run(Platform.java:317)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:287)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:147)
	at org.dyn4j.samples.UsingJogl.<init>(UsingJogl.java:173)
	at org.dyn4j.samples.UsingJogl.main(UsingJogl.java:408)
```
And
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: D:\Repos\dyn4j-samples\natives\windows-amd64\\nativewindow_awt.dll
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1820)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:624)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:63)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:106)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:487)
	at jogamp.nativewindow.NWJNILibLoader.access$000(NWJNILibLoader.java:39)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:49)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:41)
	at java.security.AccessController.doPrivileged(Native Method)
	at jogamp.nativewindow.NWJNILibLoader.loadNativeWindow(NWJNILibLoader.java:41)
	at jogamp.nativewindow.jawt.JAWTUtil.<clinit>(JAWTUtil.java:336)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.jogamp.nativewindow.NativeWindowFactory$3.run(NativeWindowFactory.java:344)
	at com.jogamp.nativewindow.NativeWindowFactory$3.run(NativeWindowFactory.java:340)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.nativewindow.NativeWindowFactory.initSingleton(NativeWindowFactory.java:340)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1721)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2297)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:988)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1004)
	at org.dyn4j.samples.UsingJogl.<init>(UsingJogl.java:173)
	at org.dyn4j.samples.UsingJogl.main(UsingJogl.java:408)
```

But After I replace the dependencies 
`<artifactId>jogl-all</artifactId>` 
`<artifactId>gluegen-rt</artifactId>` 
with
 `<artifactId>jogl-all-main</artifactId>` 
 `<artifactId>gluegen-rt-main</artifactId>`
(as described in [JogampWiki](https://jogamp.org/wiki/index.php?title=Setting_up_a_JogAmp_project_in_your_favorite_IDE#Maven) )
, those errors gone.

My environment:
IntelliJ IDEA 2022.2.1 (Community Edition)
Microsoft Windows 11 Home x64-based PC

openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)

**Comment by wnbittle** [comment]
This has been fixed (finally...)
